export const AZ_CITIES = [
  "Bakı",
  "Sumqayıt",
  "Gəncə",
  "Mingəçevir",
  "Lənkəran",
  "Şəki",
  "Yevlax",
  "Naxçıvan",
  "Şirvan",
  "Quba",
  "Xırdalan",
  "Ağdam",
  "Ağdaş",
  "Ağcabədi",
  "Ağsu",
  "Astara",
  "Balakən",
  "Bərdə",
  "Beyləqan",
  "Biləsuvar",
  "Cəlilabad",
  "Daşkəsən",
  "Füzuli",
  "Gədəbəy",
  "Goranboy",
  "Göygöl",
  "Göyçay",
  "Hacıqabul",
  "İmişli",
  "İsmayıllı",
  "Kürdəmir",
  "Laçın",
  "Lerik",
  "Masallı",
  "Naftalan",
  "Neftçala",
  "Oğuz",
  "Qax",
  "Qazax",
  "Qəbələ",
  "Qobustan",
  "Qusar",
  "Saatlı",
  "Sabirabad",
  "Salyan",
  "Samux",
  "Siyəzən",
  "Şabran",
  "Şamaxı",
  "Şəmkir",
  "Şuşa",
  "Tərtər",
  "Tovuz",
  "Ucar",
  "Xaçmaz",
  "Xankəndi",
  "Xocalı",
  "Xocavənd",
  "Yardımlı",
  "Zaqatala",
  "Zərdab",
];

export const FUEL_TYPES = [
  { value: "GASOLINE", azKey: "fuelGasoline" },
  { value: "DIESEL", azKey: "fuelDiesel" },
  { value: "HYBRID", azKey: "fuelHybrid" },
  { value: "ELECTRIC", azKey: "fuelElectric" },
  { value: "GAS", azKey: "fuelGas" },
  { value: "OTHER", azKey: "fuelOther" },
] as const;

export const PAYMENT_TYPES = [
  { value: "CASH", azKey: "paymentCash" },
  { value: "CREDIT", azKey: "paymentCredit" },
  { value: "BOTH", azKey: "paymentBoth" },
] as const;
