// İxtisas təsnifatı — 15 sektor, 223 ixtisas (İxtisas_Tesnifati sənədindən).
// Mənbə: İxtisas Təsnifatı (Sektor → İxtisas).

export interface IxtisasSector { sector: string; professions: string[]; }

export const IXTISAS_SECTORS: IxtisasSector[] = [
  { sector: "İnformasiya Texnologiyaları (İT)", professions: [
    "Frontend developer",
    "Backend developer",
    "Full-stack developer",
    "Mobil tətbiq developeri",
    "Oyun developeri",
    "DevOps mühəndisi",
    "QA / Test mühəndisi",
    "UI/UX dizayner",
    "Veb dizayner",
    "Data analitik",
    "Data Scientist / ML mühəndisi",
    "Süni intellekt mühəndisi",
    "Verilənlər bazası administratoru (DBA)",
    "Sistem administratoru",
    "Şəbəkə mühəndisi",
    "Kibertəhlükəsizlik mütəxəssisi",
    "IT texniki dəstək",
    "IT layihə meneceri / Product owner",
    "1C proqramçısı",
    "Bulud (Cloud) mühəndisi",
  ] },
  { sector: "Marketinq, Reklam və Media", professions: [
    "Marketinq meneceri",
    "SMM mütəxəssisi",
    "SEO mütəxəssisi",
    "Target / PPC mütəxəssisi",
    "Kontent meneceri",
    "Kopirayter",
    "Brend meneceri",
    "PR mütəxəssisi",
    "Reklam agenti",
    "Jurnalist / Müxbir",
    "Redaktor",
    "TV/Radio operatoru",
    "Diktor / Aparıcı",
    "Press-katib",
  ] },
  { sector: "Dizayn, İncəsənət və Əyləncə", professions: [
    "Qrafik dizayner",
    "Motion / Video dizayner",
    "İnteryer dizayneri",
    "Fotoqraf",
    "Videoqraf",
    "Foto-video montajçı",
    "Rəssam / İllüstrator",
    "Musiqiçi / Müğənni",
    "Bəstəkar",
    "DJ / Səs operatoru",
    "Aktyor",
    "Rəqqas / Xoreoqraf",
    "Tədbir təşkilatçısı (Event)",
    "Toastmaster / Aparıcı",
    "Kitabxanaçı",
    "Muzey işçisi",
    "Animator",
  ] },
  { sector: "Maliyyə, Mühasibatlıq və Hüquq", professions: [
    "Mühasib",
    "Baş mühasib",
    "Maliyyə analitiki",
    "Auditor",
    "İqtisadçı",
    "Vergi məsləhətçisi",
    "Bank operatoru",
    "Kredit mütəxəssisi",
    "Sığorta mütəxəssisi",
    "Hüquqşünas / Vəkil",
    "Notarius",
    "Kassir",
    "Kollektor / Borc üzrə mütəxəssis",
    "İnvestisiya məsləhətçisi",
  ] },
  { sector: "Ofis, İnzibati və İnsan Resursları (HR)", professions: [
    "Ofis meneceri",
    "Katib / Köməkçi (Assistant)",
    "İnzibatçı",
    "HR mütəxəssisi",
    "İşə qəbul üzrə mütəxəssis (Recruiter)",
    "Əməyin mühafizəsi mütəxəssisi",
    "Tərcüməçi",
    "Arxivçi",
    "Operator / Data entry",
    "Resepşn",
    "Sənədləşmə üzrə mütəxəssis",
  ] },
  { sector: "Ticarət və Satış", professions: [
    "Satış meneceri",
    "Satış təmsilçisi",
    "Mağaza satıcısı / Konsultant",
    "Kassir",
    "Mağaza administratoru",
    "Merçendayzer",
    "Anbardar",
    "Təchizatçı / Satınalma mütəxəssisi",
    "Topdan satış meneceri",
    "Distribütor / Agent",
    "Əmlak agenti (Rieltor)",
    "Online satış meneceri",
  ] },
  { sector: "İaşə, Qonaqlama və Turizm (HoReCa)", professions: [
    "Aşpaz",
    "Aşpaz köməkçisi",
    "Suşi ustası",
    "Qənnadçı / Pastaçı",
    "Çörəkçi (Pekar)",
    "Barmen",
    "Barista",
    "Ofisiant",
    "Restoran administratoru",
    "Otel administratoru / Resepşn",
    "Otel meneceri",
    "Turizm meneceri / Tur operator",
    "Bələdçi (Gid)",
    "Çatdırılma / Kuryer",
    "Xhost / Hostes",
  ] },
  { sector: "Səhiyyə və Tibb", professions: [
    "Həkim (ümumi təcrübə)",
    "Cərrah",
    "Stomatoloq",
    "Pediatr",
    "Kardioloq",
    "Dermatoloq",
    "Ginekoloq",
    "Nevroloq",
    "Oftalmoloq",
    "Radioloq / Rentgen mütəxəssisi",
    "Anestezioloq-reanimatoloq",
    "Tibb bacısı / Qardaşı",
    "Əczaçı / Farmasevt",
    "Laborant",
    "Psixoloq",
    "Psixiatr",
    "Diyetoloq",
    "Fizioterapevt",
    "Loqoped",
    "Massajist (tibbi)",
  ] },
  { sector: "Təhsil və Tədris", professions: [
    "Məktəb müəllimi",
    "Universitet müəllimi",
    "Xarici dil müəllimi",
    "Repetitor",
    "Uşaq bağçası tərbiyəçisi",
    "Dayə / Baxıcı",
    "Defektoloq",
    "Metodist",
    "Korporativ təlimçi",
    "Erkən inkişaf təlimçisi",
    "İmtahana hazırlıq müəllimi",
  ] },
  { sector: "Tikinti və Təmir", professions: [
    "Tikinti mühəndisi",
    "Memar",
    "Layihəçi (smeta/PUE)",
    "Usta (ümumi təmir)",
    "Bənna",
    "Betonçu / Armaturçu",
    "Suvaqçı",
    "Kafel ustası",
    "Rəngsaz / Boyaqçı",
    "Santexnik",
    "Elektrik",
    "İstilik-Havalandırma (HVAC) ustası",
    "Qaynaqçı",
    "Dülgər / Mebel ustası",
    "Kondisioner ustası",
    "Geodezist / Markşeyder",
    "Fasad / İzolyasiya ustası",
    "Gips-karton ustası",
    "Pəncərə-qapı montajçısı",
  ] },
  { sector: "İstehsal və Sənaye", professions: [
    "İstehsalat operatoru / Fəhlə",
    "CNC dəzgah operatoru",
    "Çilingər",
    "Tornaçı / Frezçi",
    "Mexanik",
    "Texnoloq",
    "Sex rəhbəri / Usta",
    "Keyfiyyətə nəzarət (OTK)",
    "Tikişçi / Dərzi",
    "Ayaqqabı ustası",
    "Yeyinti istehsalı operatoru",
    "Mebel istehsalı ustası",
    "Çap / Poliqrafiya operatoru",
    "Zərgər",
    "Saatsaz",
    "Neft-qaz istehsalı operatoru",
    "Kimyaçı-texnoloq",
  ] },
  { sector: "Nəqliyyat və Logistika", professions: [
    "Sürücü (minik avtomobili)",
    "Yük maşını sürücüsü",
    "Avtobus sürücüsü",
    "Taksi sürücüsü",
    "Kuryer / Çatdırılma sürücüsü",
    "Ekspeditor",
    "Logistika meneceri",
    "Gömrük brokeri / Bəyannaməçi",
    "Anbar müdiri",
    "Forklift operatoru",
    "Dispetçer",
    "Avtomexanik (avtoservis)",
    "Şinmontaj ustası",
    "Avto-elektrik",
    "Dənizçi / Gəmi heyəti",
    "Hava nəqliyyatı işçisi",
  ] },
  { sector: "Kənd Təsərrüfatı və Ekologiya", professions: [
    "Aqronom",
    "Fermer",
    "Baytar (Veterinar)",
    "Zootexnik (heyvandarlıq)",
    "Arıçı",
    "Balıqçı / Akvakultura mütəxəssisi",
    "Bağban",
    "Meşəçi (meşə təsərrüfatı)",
    "Suvarma / Meliorasiya mütəxəssisi",
    "Ekoloq",
    "Quşçuluq mütəxəssisi",
    "Kənd təsərrüfatı texnikası operatoru",
  ] },
  { sector: "Gözəllik, Sağlamlıq və İdman", professions: [
    "Bərbər (Barber)",
    "Hairstylist (saç ustası)",
    "Manikür / Pedikür ustası",
    "Kosmetoloq",
    "Makiyaj ustası (Vizajist)",
    "Kirpik / Qaş ustası",
    "Massajist",
    "SPA mütəxəssisi",
    "Dırnaq dizaynı ustası",
    "Fitnes məşqçisi",
    "Yoga / Pilates təlimçisi",
    "İdman məşqçisi (trener)",
    "Üzgüçülük məşqçisi",
    "Diyetoloq-nutrisioloq",
  ] },
  { sector: "Təmizlik, Mühafizə və Məişət Xidmətləri", professions: [
    "Təmizlikçi (klininq)",
    "Ev təmizliyi (xadimə)",
    "Mühafizəçi / Keşikçi",
    "Uşaq baxıcısı",
    "Yaşlı baxıcısı",
    "Quru təmizləmə / Camaşırxana işçisi",
    "Dezinfeksiya mütəxəssisi",
    "Abadlaşdırma / Bağça fəhləsi",
    "Məişət texnikası ustası (çağırışla)",
    "Kombi servis ustası",
    "Daşınma / Yükdaşıma fəhləsi",
  ] },
];

// Bütün ixtisaslar düz siyahı (təkrar olmadan).
export const ALL_IXTISAS: string[] = Array.from(new Set(IXTISAS_SECTORS.flatMap((s) => s.professions)));
